// Generated by CoffeeScript 1.6.2
(function() {
  var $, exports, qs, sfHelper;

  $ = require('jquery');

  qs = require('qs');

  /*
  
  Salesforce.com oAuth token generation
  @bugs aaylward@gmail.com <Andy Aylward>
  */


  sfHelper = function(options) {
    var data, loginServer, promise, url;

    loginServer = options.env === 'prod' ? 'login.salesforce.com' : 'test.salesforce.com';
    data = {
      grant_type: 'password',
      client_id: options.key,
      client_secret: options.secret,
      username: options.username,
      password: options.password
    };
    url = "https://" + loginServer + "/services/oauth2/token?" + (qs.stringify(data));
    promise = $.ajax({
      url: url,
      type: 'POST'
    }).promise();
    return promise;
  };

  exports = {
    sfHelper: sfHelper
  };

  module.exports = exports;

}).call(this);
