// Generated by CoffeeScript 1.6.3
(function() {
  var Q, exports, qs, request, tokenFromUsername;

  request = require('request');

  Q = require('q');

  qs = require('qs');

  /*
  
  Salesforce.com OAuth access
  @bugs aaylward@gmail.com <Andy Aylward>
  */


  tokenFromUsername = function(options) {
    var data, loginServer, post, url;
    loginServer = options.env === 'prod' ? 'login.salesforce.com' : 'test.salesforce.com';
    data = {
      grant_type: 'password',
      client_id: options.key,
      client_secret: options.secret,
      username: options.username,
      password: options.password
    };
    url = "https://" + loginServer + "/services/oauth2/token?" + (qs.stringify(data));
    post = Q.denodeify(request.post);
    return post(url);
  };

  exports = {
    tokenFromUsername: tokenFromUsername
  };

  module.exports = exports;

}).call(this);
